theme: jekyll-theme-hacker
title: Objetos 2
navbar:
  title: my web
  - Introduction: introduction
  - - Sub Menu: sub-menu-example
  - Examples: examples
  - - Headings: headings
  - - Tables: tables
  - - Code: code
